import React from "react";
import Head from "next/head";
import { Grid, Container, Typography } from "@mui/material";
import ProductCard from "../components/ProductCard/ProductCard";
import Navbar from "../components/Navbar/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>E-Commerce Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>
        <Container sx={{ py: 12 }}>
          <Typography variant="h5" sx={{ my: 3, fontWeight: "bold" }}>
            Cart
          </Typography>
          <Grid>
            <ProductCard />
          </Grid>
        </Container>
      </main>
    </>
  );
}
